## src/main/resources/config.properties
#seed=101
#repeats=1
repeats=10
seed=101

iterations=100
population=20
groups=4
alpha_makespan=0.7
beta_util=0.3
levy_lambda=1.5
levy_gamma=0.01
hosts=25
hostMips=10000
hostPes=8
hostRam=131072
hostBw=5000000
hostStorage=2000000
vms=20
vmMipsOptions=2000,3000,4000,5000
vmPes=1
vmRam=2048
vmBw=1000
vmStorage=10000
cloudletLengthMin=5000
cloudletLengthMax=30000
cloudletFileSize=300
cloudletOutputSize=300
cloudletPes=1
small_tasks=50,100
large_tasks=200,300
success_rate_threshold_ratio=1.10


#seed=275
#alpha_makespan=0.6
#beta_util=0.4
#population=30
#groups=6
#iterations=150
#levy_lambda=1.5
#levy_gamma=0.05
#repeats=3
#
## VM and host configuration
#hosts=20
#vms=40
#hostMips=12000
#hostPes=8
#hostRam=32768
#
#hostBw=100000
#hostStorage=1000000
#vmMipsOptions=2000,3000,4000,5000,6000
#vmPes=1
#vmRam=2048
#vmBw=10000
#vmStorage=10000
#
## Cloudlet distributions
#cloudletLengthMin=10000
#cloudletLengthMax=50000
#cloudletFileSize=300
#cloudletOutputSize=300
#cloudletPes=1
#
## Task regimes
#small_tasks=200,300
#large_tasks=500,700
#
## Success rate threshold
#success_rate_threshold_ratio=1.10
#
## Simulation cap to prevent infinite runtime
#sim_time_cap=1000000


#seed=917
#alpha_makespan=0.4
#beta_util=0.6
#population=60
#groups=8
#iterations=400
#levy_lambda=1.2
#levy_gamma=0.045
#repeats=3
#
#hosts=35
#vms=70
#hostMips=10000
#hostPes=8
#hostRam=32768
#hostBw=100000
#hostStorage=1000000
#vmMipsOptions=1500,2500,3000,3500,4000
#vmPes=1
#vmRam=2048
#vmBw=10000
#vmStorage=10000
#
#cloudletLengthMin=40000
#cloudletLengthMax=90000
#cloudletFileSize=300
#cloudletOutputSize=300
#cloudletPes=1
#
#small_tasks=400,600
#large_tasks=800,1000
#
#success_rate_threshold_ratio=1.15
#sim_time_cap=1000000