# src/main/resources/config.properties
seed=101
repeats=1
iterations=100
population=20
groups=4
alpha_makespan=0.7
beta_util=0.3
levy_lambda=1.5
levy_gamma=0.01
hosts=25
hostMips=10000
hostPes=8
hostRam=131072
hostBw=5000000
hostStorage=2000000
vms=20
vmMipsOptions=2000,3000,4000,5000
vmPes=1
vmRam=2048
vmBw=1000
vmStorage=10000
cloudletLengthMin=5000
cloudletLengthMax=30000
cloudletFileSize=300
cloudletOutputSize=300
cloudletPes=1
small_tasks=50,100
large_tasks=200,300
success_rate_threshold_ratio=1.10